{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "875298bf-9654-471b-af3e-af246bc5e84a",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "Publix Coupon Auto-Clipper - Login and Clip All Coupons\n",
    "Automatically logs in and clips all available digital coupons\n",
    "\"\"\"\n",
    "\n",
    "import time\n",
    "import csv\n",
    "import re\n",
    "import os\n",
    "import subprocess\n",
    "from datetime import datetime\n",
    "\n",
    "try:\n",
    "    from selenium import webdriver\n",
    "    from selenium.webdriver.common.by import By\n",
    "    from selenium.webdriver.chrome.service import Service\n",
    "    from webdriver_manager.chrome import ChromeDriverManager\n",
    "    from selenium.webdriver.chrome.options import Options\n",
    "    from selenium.webdriver.support.ui import WebDriverWait\n",
    "    from selenium.webdriver.support import expected_conditions as EC\n",
    "    from selenium.common.exceptions import TimeoutException, NoSuchElementException\n",
    "    SELENIUM_OK = True\n",
    "except ImportError:\n",
    "    SELENIUM_OK = False\n",
    "\n",
    "def setup_driver():\n",
    "    \"\"\"Setup Chrome driver with better error handling\"\"\"\n",
    "    options = Options()\n",
    "    # Comment out to see browser (recommended for login)\n",
    "    # options.add_argument(\"--headless\")\n",
    "    options.add_argument(\"--no-sandbox\")\n",
    "    options.add_argument(\"--disable-dev-shm-usage\")\n",
    "    options.add_argument(\"--window-size=1920,1080\")\n",
    "    options.add_argument(\"--disable-extensions\")\n",
    "    options.add_argument(\"--disable-gpu\")\n",
    "    \n",
    "    try:\n",
    "        # Method 1: Try ChromeDriverManager with cache clearing\n",
    "        print(\"🔧 Attempting to setup ChromeDriver...\")\n",
    "        \n",
    "        # Clear any existing chromedriver processes\n",
    "        import subprocess\n",
    "        try:\n",
    "            subprocess.run([\"taskkill\", \"/f\", \"/im\", \"chromedriver.exe\"], \n",
    "                         capture_output=True, check=False)\n",
    "        except:\n",
    "            pass\n",
    "        \n",
    "        service = Service(ChromeDriverManager().install())\n",
    "        return webdriver.Chrome(service=service, options=options)\n",
    "        \n",
    "    except PermissionError as e:\n",
    "        print(f\"⚠️  Permission error with ChromeDriverManager: {e}\")\n",
    "        print(\"🔧 Trying alternative methods...\")\n",
    "        \n",
    "        # Method 2: Try to use system Chrome without ChromeDriverManager\n",
    "        try:\n",
    "            print(\"   📝 Attempting to use system Chrome...\")\n",
    "            return webdriver.Chrome(options=options)\n",
    "        except Exception as e2:\n",
    "            print(f\"   ❌ System Chrome failed: {e2}\")\n",
    "            \n",
    "        # Method 3: Manual ChromeDriver path (if exists)\n",
    "        try:\n",
    "            print(\"   📝 Trying manual ChromeDriver path...\")\n",
    "            # Common ChromeDriver locations\n",
    "            manual_paths = [\n",
    "                r\"C:\\chromedriver.exe\",\n",
    "                r\"C:\\Program Files\\ChromeDriver\\chromedriver.exe\",\n",
    "                r\"C:\\Tools\\chromedriver.exe\"\n",
    "            ]\n",
    "            \n",
    "            for path in manual_paths:\n",
    "                if os.path.exists(path):\n",
    "                    service = Service(path)\n",
    "                    return webdriver.Chrome(service=service, options=options)\n",
    "            \n",
    "            print(\"   ❌ No manual ChromeDriver found\")\n",
    "            \n",
    "        except Exception as e3:\n",
    "            print(f\"   ❌ Manual path failed: {e3}\")\n",
    "        \n",
    "        # If all else fails, provide instructions\n",
    "        print(\"\\n\" + \"=\"*60)\n",
    "        print(\"❌ CHROMEDRIVER SETUP FAILED\")\n",
    "        print(\"=\"*60)\n",
    "        print(\"💡 SOLUTIONS:\")\n",
    "        print(\"\\n1. 🔄 RESTART AND RETRY:\")\n",
    "        print(\"   - Close ALL Chrome browser windows\")\n",
    "        print(\"   - Restart your Python environment\")\n",
    "        print(\"   - Run the script again\")\n",
    "        \n",
    "        print(\"\\n2. 🗑️  CLEAR CHROMEDRIVER CACHE:\")\n",
    "        print(\"   - Delete folder: C:\\\\Users\\\\ryane\\\\.wdm\")\n",
    "        print(\"   - Run script again\")\n",
    "        \n",
    "        print(\"\\n3. 📥 MANUAL CHROMEDRIVER SETUP:\")\n",
    "        print(\"   - Download ChromeDriver from: https://chromedriver.chromium.org/\")\n",
    "        print(\"   - Extract chromedriver.exe to C:\\\\chromedriver.exe\")\n",
    "        print(\"   - Run script again\")\n",
    "        \n",
    "        print(\"\\n4. 🔐 RUN AS ADMINISTRATOR:\")\n",
    "        print(\"   - Right-click your Python IDE\")\n",
    "        print(\"   - Select 'Run as administrator'\")\n",
    "        print(\"   - Try again\")\n",
    "        \n",
    "        raise Exception(\"ChromeDriver setup failed - see solutions above\")\n",
    "\n",
    "def login_to_publix(driver):\n",
    "    \"\"\"Handle Publix login process\"\"\"\n",
    "    print(\"🔐 Starting login process...\")\n",
    "    \n",
    "    try:\n",
    "        # Go to Publix main page first\n",
    "        driver.get(\"https://www.publix.com\")\n",
    "        time.sleep(3)\n",
    "        \n",
    "        # Look for login/sign in button\n",
    "        login_selectors = [\n",
    "            \"//a[contains(text(), 'Log in')]\",\n",
    "            \"//a[contains(text(), 'Sign in')]\",\n",
    "            \"//button[contains(text(), 'Log in')]\",\n",
    "            \"//button[contains(text(), 'Sign in')]\",\n",
    "            \"//*[@data-testid='header-account-sign-in']\",\n",
    "            \"//a[@href='/login']\"\n",
    "        ]\n",
    "        \n",
    "        login_clicked = False\n",
    "        for selector in login_selectors:\n",
    "            try:\n",
    "                login_button = driver.find_element(By.XPATH, selector)\n",
    "                if login_button.is_displayed():\n",
    "                    print(\"   ✅ Found login button, clicking...\")\n",
    "                    login_button.click()\n",
    "                    login_clicked = True\n",
    "                    break\n",
    "            except:\n",
    "                continue\n",
    "        \n",
    "        if not login_clicked:\n",
    "            print(\"   ⚠️  Couldn't find login button automatically\")\n",
    "            print(\"   📱 Please manually click the login/sign in button\")\n",
    "            input(\"   ⏳ Press Enter after you've clicked the login button...\")\n",
    "        \n",
    "        time.sleep(3)\n",
    "        \n",
    "        # Wait for login form or check if already logged in\n",
    "        print(\"   📝 Waiting for login form or checking if already logged in...\")\n",
    "        \n",
    "        # Check if we're already logged in by looking for account indicators\n",
    "        logged_in_indicators = [\n",
    "            \"//a[contains(text(), 'My Account')]\",\n",
    "            \"//a[contains(text(), 'Account')]\",\n",
    "            \"//*[contains(@class, 'account')]//a\",\n",
    "            \"//button[contains(text(), 'Log out')]\"\n",
    "        ]\n",
    "        \n",
    "        already_logged_in = False\n",
    "        for indicator in logged_in_indicators:\n",
    "            try:\n",
    "                element = driver.find_element(By.XPATH, indicator)\n",
    "                if element.is_displayed():\n",
    "                    print(\"   ✅ Already logged in!\")\n",
    "                    already_logged_in = True\n",
    "                    break\n",
    "            except:\n",
    "                continue\n",
    "        \n",
    "        if not already_logged_in:\n",
    "            print(\"   📧 Please enter your login credentials manually\")\n",
    "            print(\"   ⏳ The script will wait for you to complete the login process...\")\n",
    "            print(\"   💡 After logging in, press Enter to continue\")\n",
    "            input(\"   ⌨️  Press Enter when you've successfully logged in...\")\n",
    "        \n",
    "        # Verify login was successful\n",
    "        time.sleep(2)\n",
    "        print(\"   ✅ Login process completed!\")\n",
    "        return True\n",
    "        \n",
    "    except Exception as e:\n",
    "        print(f\"   ❌ Login error: {e}\")\n",
    "        print(\"   💡 Please log in manually and then press Enter\")\n",
    "        input(\"   ⌨️  Press Enter when ready to continue...\")\n",
    "        return True\n",
    "\n",
    "def click_load_more_all(driver, max_times=10):\n",
    "    \"\"\"Click Load More button until no more content loads\"\"\"\n",
    "    print(f\"🔄 Loading all coupons (max {max_times} attempts)...\")\n",
    "    \n",
    "    clicks_made = 0\n",
    "    consecutive_failures = 0\n",
    "    \n",
    "    for i in range(max_times):\n",
    "        print(f\"   🔘 Load more attempt {i+1}/{max_times}\")\n",
    "        \n",
    "        # Scroll to bottom to find the button\n",
    "        driver.execute_script(\"window.scrollTo(0, document.body.scrollHeight);\")\n",
    "        time.sleep(2)\n",
    "        \n",
    "        # Try to find the Load More button\n",
    "        button_found = False\n",
    "        \n",
    "        try:\n",
    "            # Multiple selectors for Load More button\n",
    "            load_more_selectors = [\n",
    "                \"//span[contains(text(), 'Load more')]\",\n",
    "                \"//button[contains(text(), 'Load more')]\",\n",
    "                \"//*[contains(@class, 'load-more')]\",\n",
    "                \"//a[contains(text(), 'Load more')]\"\n",
    "            ]\n",
    "            \n",
    "            load_more_element = None\n",
    "            for selector in load_more_selectors:\n",
    "                try:\n",
    "                    load_more_element = driver.find_element(By.XPATH, selector)\n",
    "                    if load_more_element.is_displayed() and load_more_element.is_enabled():\n",
    "                        break\n",
    "                except:\n",
    "                    continue\n",
    "            \n",
    "            if load_more_element and load_more_element.is_displayed() and load_more_element.is_enabled():\n",
    "                print(f\"      ✅ Found Load More button!\")\n",
    "                \n",
    "                # Scroll to the button\n",
    "                driver.execute_script(\"arguments[0].scrollIntoView({block: 'center'});\", load_more_element)\n",
    "                time.sleep(1)\n",
    "                \n",
    "                # Click it\n",
    "                try:\n",
    "                    load_more_element.click()\n",
    "                    print(f\"      ✅ Successfully clicked!\")\n",
    "                except:\n",
    "                    driver.execute_script(\"arguments[0].click();\", load_more_element)\n",
    "                    print(f\"      ✅ Successfully clicked with JavaScript!\")\n",
    "                \n",
    "                button_found = True\n",
    "                clicks_made += 1\n",
    "                consecutive_failures = 0\n",
    "                print(f\"      ⏳ Waiting for content to load...\")\n",
    "                time.sleep(8)  # Wait longer for content to load\n",
    "                \n",
    "        except:\n",
    "            consecutive_failures += 1\n",
    "            print(f\"   ❌ No Load More button found on attempt {i+1}\")\n",
    "        \n",
    "        if not button_found:\n",
    "            consecutive_failures += 1\n",
    "            if consecutive_failures >= 3:\n",
    "                print(f\"   💡 No more Load More buttons found - probably loaded all coupons!\")\n",
    "                break\n",
    "    \n",
    "    print(f\"🏁 Finished loading content ({clicks_made} successful clicks)\")\n",
    "    return clicks_made\n",
    "\n",
    "def clip_all_coupons(driver):\n",
    "    \"\"\"Find and clip all available coupons\"\"\"\n",
    "    print(\"✂️  Starting to clip all coupons...\")\n",
    "    \n",
    "    # Scroll to top first\n",
    "    driver.execute_script(\"window.scrollTo(0, 0);\")\n",
    "    time.sleep(2)\n",
    "    \n",
    "    clipped_count = 0\n",
    "    already_clipped_count = 0\n",
    "    error_count = 0\n",
    "    \n",
    "    # Multiple selectors for clip coupon buttons\n",
    "    clip_selectors = [\n",
    "        \"//button[contains(text(), 'Clip coupon')]\",\n",
    "        \"//span[contains(text(), 'Clip coupon')]\",\n",
    "        \"//*[contains(@class, 'clip') and contains(text(), 'coupon')]\",\n",
    "        \"//a[contains(text(), 'Clip coupon')]\",\n",
    "        \"//*[@data-testid='clip-coupon']\",\n",
    "        \"//*[contains(@aria-label, 'clip')]\"\n",
    "    ]\n",
    "    \n",
    "    # Find all clip buttons\n",
    "    all_clip_buttons = []\n",
    "    for selector in clip_selectors:\n",
    "        try:\n",
    "            buttons = driver.find_elements(By.XPATH, selector)\n",
    "            all_clip_buttons.extend(buttons)\n",
    "        except:\n",
    "            continue\n",
    "    \n",
    "    # Remove duplicates by keeping track of button locations\n",
    "    unique_buttons = []\n",
    "    seen_locations = set()\n",
    "    \n",
    "    for button in all_clip_buttons:\n",
    "        try:\n",
    "            location = (button.location['x'], button.location['y'])\n",
    "            if location not in seen_locations:\n",
    "                seen_locations.add(location)\n",
    "                unique_buttons.append(button)\n",
    "        except:\n",
    "            continue\n",
    "    \n",
    "    print(f\"   📊 Found {len(unique_buttons)} potential clip buttons\")\n",
    "    \n",
    "    # Process each button\n",
    "    for i, button in enumerate(unique_buttons):\n",
    "        try:\n",
    "            # Scroll to button\n",
    "            driver.execute_script(\"arguments[0].scrollIntoView({block: 'center'});\", button)\n",
    "            time.sleep(1)\n",
    "            \n",
    "            # Check if button is clickable\n",
    "            if not button.is_displayed() or not button.is_enabled():\n",
    "                continue\n",
    "            \n",
    "            # Check button text to see if already clipped\n",
    "            button_text = button.text.lower()\n",
    "            \n",
    "            if 'clipped' in button_text or 'added' in button_text:\n",
    "                already_clipped_count += 1\n",
    "                print(f\"   ✅ Coupon {i+1}: Already clipped\")\n",
    "                continue\n",
    "            \n",
    "            # Try to click the button\n",
    "            try:\n",
    "                button.click()\n",
    "                clipped_count += 1\n",
    "                print(f\"   🎯 Coupon {i+1}: Successfully clipped!\")\n",
    "                time.sleep(1)  # Brief pause between clicks\n",
    "                \n",
    "            except Exception as click_error:\n",
    "                # Try JavaScript click as backup\n",
    "                try:\n",
    "                    driver.execute_script(\"arguments[0].click();\", button)\n",
    "                    clipped_count += 1\n",
    "                    print(f\"   🎯 Coupon {i+1}: Successfully clipped (JS)!\")\n",
    "                    time.sleep(1)\n",
    "                except:\n",
    "                    error_count += 1\n",
    "                    print(f\"   ❌ Coupon {i+1}: Failed to clip\")\n",
    "            \n",
    "        except Exception as e:\n",
    "            error_count += 1\n",
    "            print(f\"   ❌ Coupon {i+1}: Error - {str(e)[:50]}\")\n",
    "            continue\n",
    "    \n",
    "    # Summary\n",
    "    print(\"=\"*60)\n",
    "    print(f\"🎉 CLIPPING COMPLETE!\")\n",
    "    print(f\"   ✅ Successfully clipped: {clipped_count}\")\n",
    "    print(f\"   ✅ Already clipped: {already_clipped_count}\")\n",
    "    print(f\"   ❌ Errors: {error_count}\")\n",
    "    print(f\"   📊 Total processed: {clipped_count + already_clipped_count + error_count}\")\n",
    "    print(\"=\"*60)\n",
    "    \n",
    "    return {\n",
    "        'clipped': clipped_count,\n",
    "        'already_clipped': already_clipped_count,\n",
    "        'errors': error_count,\n",
    "        'total': clipped_count + already_clipped_count + error_count\n",
    "    }\n",
    "\n",
    "def save_clipping_report(results):\n",
    "    \"\"\"Save a report of the clipping session\"\"\"\n",
    "    target_dir = r\"C:\\Users\\ryane\\OneDrive\\Documents\\Coupons\"\n",
    "    \n",
    "    try:\n",
    "        os.makedirs(target_dir, exist_ok=True)\n",
    "        print(f\"📁 Saving report to: {target_dir}\")\n",
    "    except:\n",
    "        target_dir = \".\"\n",
    "        print(\"📁 Saving report to current directory\")\n",
    "    \n",
    "    timestamp = datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
    "    filename = f\"publix_clipping_report_{timestamp}.txt\"\n",
    "    filepath = os.path.join(target_dir, filename)\n",
    "    \n",
    "    try:\n",
    "        with open(filepath, 'w', encoding='utf-8') as f:\n",
    "            f.write(\"Publix Coupon Clipping Report\\n\")\n",
    "            f.write(\"=\"*40 + \"\\n\")\n",
    "            f.write(f\"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\\n\")\n",
    "            f.write(f\"Successfully clipped: {results['clipped']}\\n\")\n",
    "            f.write(f\"Already clipped: {results['already_clipped']}\\n\")\n",
    "            f.write(f\"Errors: {results['errors']}\\n\")\n",
    "            f.write(f\"Total processed: {results['total']}\\n\")\n",
    "            f.write(\"=\"*40 + \"\\n\")\n",
    "        \n",
    "        print(f\"✅ Report saved to: {filepath}\")\n",
    "        \n",
    "    except Exception as e:\n",
    "        print(f\"❌ Report save error: {e}\")\n",
    "\n",
    "def main():\n",
    "    \"\"\"Main function\"\"\"\n",
    "    print(\"🏪 Publix Coupon Auto-Clipper\")\n",
    "    print(\"Login and clip all digital coupons!\")\n",
    "    print(\"=\"*50)\n",
    "    \n",
    "    if not SELENIUM_OK:\n",
    "        print(\"❌ Install required packages:\")\n",
    "        print(\"   pip install selenium webdriver-manager\")\n",
    "        return\n",
    "    \n",
    "    driver = setup_driver()\n",
    "    \n",
    "    try:\n",
    "        # Step 1: Login\n",
    "        login_success = login_to_publix(driver)\n",
    "        if not login_success:\n",
    "            print(\"❌ Login failed - exiting\")\n",
    "            return\n",
    "        \n",
    "        # Step 2: Navigate to coupons page\n",
    "        print(\"📱 Loading digital coupons page...\")\n",
    "        driver.get(\"https://www.publix.com/savings/digital-coupons\")\n",
    "        time.sleep(5)\n",
    "        \n",
    "        # Step 3: Load all coupons\n",
    "        clicks_made = click_load_more_all(driver, max_times=15)\n",
    "        \n",
    "        # Step 4: Clip all coupons\n",
    "        results = clip_all_coupons(driver)\n",
    "        \n",
    "        # Step 5: Save report\n",
    "        save_clipping_report(results)\n",
    "        \n",
    "        # Final message\n",
    "        if results['clipped'] > 0:\n",
    "            print(f\"\\n🎉 SUCCESS! Clipped {results['clipped']} new coupons!\")\n",
    "        else:\n",
    "            print(f\"\\n✅ No new coupons to clip (found {results['already_clipped']} already clipped)\")\n",
    "        \n",
    "        print(\"💡 Check your Publix account to verify the coupons were added\")\n",
    "        \n",
    "    except Exception as e:\n",
    "        print(f\"❌ Error: {e}\")\n",
    "        \n",
    "    finally:\n",
    "        print(\"\\n🔄 Browser will close in 10 seconds...\")\n",
    "        print(\"💡 You can close it manually if needed\")\n",
    "        time.sleep(10)\n",
    "        try:\n",
    "            driver.quit()\n",
    "        except:\n",
    "            pass\n",
    "        print(\"✅ Complete!\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
